from flow.networks.figure_eight import ADDITIONAL_NET_PARAMS

# ENV1_NET PARAMS
ADDITIONAL_NET_PARAMS_ENV1 = ADDITIONAL_NET_PARAMS.copy()
ADDITIONAL_NET_PARAMS_ENV1["lanes"] = 2
ADDITIONAL_NET_PARAMS_ENV1["resolution"] = 40
ADDITIONAL_NET_PARAMS_ENV1["radius_ring"] = 60
